//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BancoCliente.BancoService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://banco.org/", ConfigurationName="BancoService.BancoServiceSoap")]
    public interface BancoServiceSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento numeroCuenta del espacio de nombres http://banco.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://banco.org/VerificarSaldoParaCompra", ReplyAction="*")]
        BancoCliente.BancoService.VerificarSaldoParaCompraResponse VerificarSaldoParaCompra(BancoCliente.BancoService.VerificarSaldoParaCompraRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://banco.org/VerificarSaldoParaCompra", ReplyAction="*")]
        System.Threading.Tasks.Task<BancoCliente.BancoService.VerificarSaldoParaCompraResponse> VerificarSaldoParaCompraAsync(BancoCliente.BancoService.VerificarSaldoParaCompraRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class VerificarSaldoParaCompraRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="VerificarSaldoParaCompra", Namespace="http://banco.org/", Order=0)]
        public BancoCliente.BancoService.VerificarSaldoParaCompraRequestBody Body;
        
        public VerificarSaldoParaCompraRequest() {
        }
        
        public VerificarSaldoParaCompraRequest(BancoCliente.BancoService.VerificarSaldoParaCompraRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://banco.org/")]
    public partial class VerificarSaldoParaCompraRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string numeroCuenta;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string tipoCuenta;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public decimal montoCompra;
        
        public VerificarSaldoParaCompraRequestBody() {
        }
        
        public VerificarSaldoParaCompraRequestBody(string numeroCuenta, string tipoCuenta, decimal montoCompra) {
            this.numeroCuenta = numeroCuenta;
            this.tipoCuenta = tipoCuenta;
            this.montoCompra = montoCompra;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class VerificarSaldoParaCompraResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="VerificarSaldoParaCompraResponse", Namespace="http://banco.org/", Order=0)]
        public BancoCliente.BancoService.VerificarSaldoParaCompraResponseBody Body;
        
        public VerificarSaldoParaCompraResponse() {
        }
        
        public VerificarSaldoParaCompraResponse(BancoCliente.BancoService.VerificarSaldoParaCompraResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://banco.org/")]
    public partial class VerificarSaldoParaCompraResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool VerificarSaldoParaCompraResult;
        
        public VerificarSaldoParaCompraResponseBody() {
        }
        
        public VerificarSaldoParaCompraResponseBody(bool VerificarSaldoParaCompraResult) {
            this.VerificarSaldoParaCompraResult = VerificarSaldoParaCompraResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface BancoServiceSoapChannel : BancoCliente.BancoService.BancoServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BancoServiceSoapClient : System.ServiceModel.ClientBase<BancoCliente.BancoService.BancoServiceSoap>, BancoCliente.BancoService.BancoServiceSoap {
        
        public BancoServiceSoapClient() {
        }
        
        public BancoServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BancoServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BancoServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BancoServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BancoCliente.BancoService.VerificarSaldoParaCompraResponse BancoCliente.BancoService.BancoServiceSoap.VerificarSaldoParaCompra(BancoCliente.BancoService.VerificarSaldoParaCompraRequest request) {
            return base.Channel.VerificarSaldoParaCompra(request);
        }
        
        public bool VerificarSaldoParaCompra(string numeroCuenta, string tipoCuenta, decimal montoCompra) {
            BancoCliente.BancoService.VerificarSaldoParaCompraRequest inValue = new BancoCliente.BancoService.VerificarSaldoParaCompraRequest();
            inValue.Body = new BancoCliente.BancoService.VerificarSaldoParaCompraRequestBody();
            inValue.Body.numeroCuenta = numeroCuenta;
            inValue.Body.tipoCuenta = tipoCuenta;
            inValue.Body.montoCompra = montoCompra;
            BancoCliente.BancoService.VerificarSaldoParaCompraResponse retVal = ((BancoCliente.BancoService.BancoServiceSoap)(this)).VerificarSaldoParaCompra(inValue);
            return retVal.Body.VerificarSaldoParaCompraResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BancoCliente.BancoService.VerificarSaldoParaCompraResponse> BancoCliente.BancoService.BancoServiceSoap.VerificarSaldoParaCompraAsync(BancoCliente.BancoService.VerificarSaldoParaCompraRequest request) {
            return base.Channel.VerificarSaldoParaCompraAsync(request);
        }
        
        public System.Threading.Tasks.Task<BancoCliente.BancoService.VerificarSaldoParaCompraResponse> VerificarSaldoParaCompraAsync(string numeroCuenta, string tipoCuenta, decimal montoCompra) {
            BancoCliente.BancoService.VerificarSaldoParaCompraRequest inValue = new BancoCliente.BancoService.VerificarSaldoParaCompraRequest();
            inValue.Body = new BancoCliente.BancoService.VerificarSaldoParaCompraRequestBody();
            inValue.Body.numeroCuenta = numeroCuenta;
            inValue.Body.tipoCuenta = tipoCuenta;
            inValue.Body.montoCompra = montoCompra;
            return ((BancoCliente.BancoService.BancoServiceSoap)(this)).VerificarSaldoParaCompraAsync(inValue);
        }
    }
}
